# Generated by Django 5.2.14 on 2026-06-07 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('call_sid', models.CharField(max_length=255, unique=True)),
                ('stream_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('from_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('to_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, default='incoming', max_length=20)),
                ('call_state', models.CharField(choices=[('greeting', 'Greeting'), ('mode_selection', 'Mode Selection'), ('identity_check', 'Identity Check'), ('unknown_caller_choice', 'Unknown Caller Choice'), ('intake', 'Intake'), ('conversation', 'Conversation'), ('summary_confirm', 'Summary Confirm'), ('ended', 'Ended')], db_index=True, default='greeting', max_length=50)),
                ('selected_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('end_reason', models.CharField(blank=True, help_text='Why the call ended: caller_hangup, no_input_timeout, ai_ended, error', max_length=255, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='telephony.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('delivery_status', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='telephony.call')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptTurn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq_number', models.IntegerField()),
                ('speaker', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='telephony.call')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
