# Generated by Django 5.2.14 on 2026-06-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Token usage breakdown for this call. Keys: prompt_tokens, completion_tokens, thinking_tokens, total_tokens, total_audio_tokens.'),
        ),
        migrations.AddField(
            model_name='summary',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Token usage breakdown for summary generation. Keys: prompt_tokens, completion_tokens, total_tokens.'),
        ),
    ]
