# Generated by Django 5.2.14 on 2026-06-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_call_completed_on_call_direction_call_from_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='telephony.call', unique=True),
        ),
    ]
