# Generated by Django 5.2.14 on 2026-06-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_alter_summary_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='caller_number',
        ),
        migrations.AddField(
            model_name='call',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified'),
        ),
        migrations.AddField(
            model_name='transcriptturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified'),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created'),
        ),
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='call',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Datetime when this object was last modified'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='telephony.call'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transcriptturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime when this object was created'),
        ),
        migrations.AlterField(
            model_name='transcriptturn',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
